blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions & Meme Ideas
    url: https://github.com/imMamdouhaboammar/meme-marketing/discussions
    about: Brainstorm relatable situations, propose cinema quotes, or ask questions!
